### ISSUE TITLE
能不能增加个x264和x265

### ISSUE THREAD

**Issue by takutasa** [zyzsdy/NegativeEncoder#12]
现在日常使用以及字幕组压制基本会用X265，上传网站视频用x264，但是现在用vs都是要安装Python运行库，太麻烦，不按照python的规则来就是出现问题，所以就是因为这个原因就不想碰vs。

**Comment by zyzsdy** [comment]
本项目的存在意义并不是这样的。可能以后会加，不过应该相当长的一段时间内不会加的。
