### ISSUE TITLE
添加nvencc中的vbr-quality参数

### ISSUE THREAD

**Issue by aliofwind** [zyzsdy/NegativeEncoder#13]
nvencc提供了--vbr-quality参数，搭配--vbrhq 0可以实现类似于x264中crf的效果，比cqp模式更节省码率，在--vbrhq设置了码率之后搭配--vbr-quality参数，也可以在一定程度上调整视频的画质

**Comment by zyzsdy** [comment]
动动提出，希望增加 --gop-len 参数、 --max-bitrate 参数 和 --d3d11参数
这些计划一并实现
