### ISSUE TITLE
Holy菊苣的VSFilter更新了

### ISSUE THREAD

**Issue by qwe7989199** [zyzsdy/NegativeEncoder#19]
1.支持non-ascii文件名了，不用encode gbk解决了
2.支持yuv420p16了
3.代码同步mpcbe 153了
可以考虑换掉原来的了

**Comment by zyzsdy** [comment]
惊了，时隔三年居然能更新了
tql

是这个吧（https://github.com/HomeOfVapourSynthEvolution/VSFilter/releases）
链接先放这里下次好找，这波issue挨个处理一下然后就更新

**Comment by qwe7989199** [comment]
> 惊了，时隔三年居然能更新了
> tql
> 
> 是这个吧（[https://github.com/HomeOfVapourSynthEvolution/VSFilter/releases）](https://github.com/HomeOfVapourSynthEvolution/VSFilter/releases%EF%BC%89)
> 链接先放这里下次好找，这波issue挨个处理一下然后就更新

雷鸣菊苣的，我放这了：https://github.com/sorayuki/VSFilterMod

**Comment by zyzsdy** [comment]
Done.

Release version upload later.
