### ISSUE TITLE
有关音频同步

### ISSUE THREAD

**Issue by zyzsdy** [zyzsdy/NegativeEncoder#2]
今天不是提交了一个思路（ d8405f3 ）用ffmpeg强行处理一些厄介vfr源嘛。结果发现nico的一些vfr正常了，fresh的一些vfr样本压出来还是音画不同步？

为什么呢？经动动提示，发现是nico的那些vfr里面只有video有timecode，那么只需要给视频增加或者减少一些帧，音频不变就能对的上。
但是fresh的某些vfr样本，video和audio里都有timecode，那么就不仅要给视频增加额外的重复帧，音频也要调整一下。

找了下ffmpeg的api发现还真有，调整了几组参数以后成功了。
记录一下：

```bash
ffmpeg -y -i "input.mp4" -an -pix_fmt yuv420p -f yuv4mpegpipe - | qsvencc --y4m -i - -o "videoTemp.mp4" --la-icq 20 
ffmpeg -y -i "input.mp4" -vn -sn -v 0 -c:a pcm_s16le -af aresample=async=1 -f wav pipe: | neroAacEnc -ignorelength -lc -br 192000 -if - -of "aacTemp.aac"
MP4Box.exe -add "videoTemp.mp4#trackID=1:par=1:1:name=" -add "aacTemp.aac:name=" -new "output.mp4"
```

有空了编码到本项目里。

另外：现在的GUI很难支撑更复杂的功能了，比如说 #1 ，我正在考虑换一种GUI构造。

**Comment by VegeHime** [comment]
唔…… 加入队列的时候开始压制有点迷 另外AVS如果同时压制貌似会炸
大大能给留个群号交流吗

**Comment by zyzsdy** [comment]
有点迷具体是指什么？

另外AVS同时压制出错的具体问题，麻烦**新开一个issue**说明一下。

**Comment by VegeHime** [comment]
应该是我对你程序的理解有问题了 我是顺着批量压制的逻辑来的

**Comment by A1exInamin** [comment]
使用上述命令处理部分 VFR 视频时出现了音频断点的问题
出现问题的文件: https://mega.nz/#!3lVzDCCY!PiUc_brCrejQfH93U0VW_fZ4t-HBS6R-wCRF7c6U9q4
文件描述:
`pico14.mkv` 为原始档案（使用 `Minyami` 直接从 AbemaTV 下载得到）
`pico14.aac` 为使用命令 `ffmpeg -y -i "input.mp4" -vn -sn -v 0 -c:a pcm_s16le -af aresample=async=1 -f wav pipe: | neroAacEnc -ignorelength -lc -br 192000 -if - -of "aacTemp.aac"` 处理后得到的音频文件
`pico14_cfr.mkv` 为使用命令 `ffmpeg -y -i "input.mp4" -an -pix_fmt yuv420p -f yuv4mpegpipe - | qsvencc --y4m -i - -o "videoTemp.mp4"` 得到的视频文件
`pico14_cfr_mkv.mkv` 为上述两个文件合并后得到的视频文件

具体表现:
![音频断点示例](https://ww1.sinaimg.cn/large/7b537b1bly1fvzb6xoewmj207a04amxn.jpg)
![音频断点示例](https://ww1.sinaimg.cn/large/7b537b1bly1fvzb89fo0fj204q04ut90.jpg)

**Comment by zyzsdy** [comment]
这个问题我们自己也碰到过。
动动还没研究出解决方案来。

**Comment by Last-Order** [comment]
https://github.com/rigaya/NVEnc/issues/78

**Comment by Last-Order** [comment]
https://t.bilibili.com/187379785217884686 这个说不定管用？

**Comment by zyzsdy** [comment]
@A1exInamin 今天空空（@Last-Order ）仔细分析了这个问题，主要是音频时间轴经过多次转换的累计误差。

简单的说，如果一段视频从高精度时间戳的容器（比如ts）转换到低精度时间戳的容器（比如rtmp），就会丢失一部分时间戳精度，造成一个轻微偏移。

如果这个低精度时间戳的视频流再次被转换回高精度时间戳的格式，比如我们录制直播流的时候，就会产生一个误差。minyami的处理过程可能将每个ts分段的误差累积在一起，导致每一段的末尾出现了一个较大的gap。

目前空空已经着手处理这个问题，但是他似乎没有有效的解决方案。如果你有什么好的方案，也请与我（或者空空）交流。

**Comment by zyzsdy** [comment]
> 使用上述命令处理部分 VFR 视频时出现了音频断点的问题
> 出现问题的文件: https://mega.nz/#!3lVzDCCY!PiUc_brCrejQfH93U0VW_fZ4t-HBS6R-wCRF7c6U9q4
> 文件描述:
> `pico14.mkv` 为原始档案（使用 `Minyami` 直接从 AbemaTV 下载得到）
> `pico14.aac` 为使用命令 `ffmpeg -y -i "input.mp4" -vn -sn -v 0 -c:a pcm_s16le -af aresample=async=1 -f wav pipe: | neroAacEnc -ignorelength -lc -br 192000 -if - -of "aacTemp.aac"` 处理后得到的音频文件
> `pico14_cfr.mkv` 为使用命令 `ffmpeg -y -i "input.mp4" -an -pix_fmt yuv420p -f yuv4mpegpipe - | qsvencc --y4m -i - -o "videoTemp.mp4"` 得到的视频文件
> `pico14_cfr_mkv.mkv` 为上述两个文件合并后得到的视频文件
> 
> 具体表现:
> ![音频断点示例](https://camo.githubusercontent.com/f75cc1999338c562d9bde0ddd914402962f9dedf/68747470733a2f2f7777312e73696e61696d672e636e2f6c617267652f37623533376231626c793166767a6236786f65776d6a323037613034616d786e2e6a7067)
> ![音频断点示例](https://camo.githubusercontent.com/f56a00271c207159d8f79160322ca1fcab760837/68747470733a2f2f7777312e73696e61696d672e636e2f6c617267652f37623533376231626c793166767a623839666f30666a323034713034757439302e6a7067)

抱歉隔了快一年后回复

目前这个原因已经很清楚了，mkv的时间戳也是低精度格式，于是在低精度到高精度的各种转换时候，逐渐产生了累积误差。

minyami早已于去年年底就不再以mkv作为默认格式，可以说已经从源头上避免了这个问题。

NegativeEncoder也将在之后的更新中，不再将mkv作为推荐格式。
