### ISSUE TITLE
VFR 视频处理

### ISSUE THREAD

**Issue by Last-Order** [zyzsdy/NegativeEncoder#3]
采用 nvencc 可以直接将 VFR 视频转换为 CFR。
之前对某些视频存在无法处理的问题，目前作者已经在4.11版本修复了该问题（https://github.com/rigaya/NVEnc/issues/64）。

希望增加直接使用 nvencc 处理的模式。

参考命令
```
NVEncC64.exe -i "F:\vfr.mp4" --avhw --audio-codec --audio-bitrate 192 --avsync forcecfr --fps 30 -o "F:\cfr2.mp4" --cqp 21
```

**Comment by zyzsdy** [comment]
下个版本加上，顺便和 #2 一起搞了。

**Comment by zyzsdy** [comment]
fixed in 7fbe69a
