### ISSUE TITLE
是时候更新环境了

### ISSUE THREAD

**Issue by BingLingGroup** [zyzsdy/NegativeEncoder#32]
由于消极压制release里的vslsmash太旧了，压制VP9有掉帧问题。尝试更换[Avisynth](http://avisynth.nl/index.php/LSMASHSource)官网中的最新版[L-SMASH](https://github.com/HolyWu/L-SMASH-Works)发现旧版Vapoursynth不支持，建议升级环境。同时建议不要把依赖全扔到一个文件夹里，感觉分不清，也不方便使用者更新

脚本
```Python
from vapoursynth import core, YUV420P8

VIDEO_PATH = r'xxx.webm'

core.std.LoadPlugin(path=r"LSMASHSource.dll")

video = core.lsmas.LWLibavSource(VIDEO_PATH)
video = core.resize.Bicubic(video, format=YUV420P8)
video.set_output()

```

错误日志
```
_nevs_batTemp.bat 
Script evaluation failed:
Python exception: Core only supports API R3.5 but the loaded plugin requires API R3.6; Filename: LSMASHSource.dll; Name: LSMASHSource for VapourSynth

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 1927, in vapoursynth.vpy_evaluateScript
  File "src\cython\vapoursynth.pyx", line 1928, in vapoursynth.vpy_evaluateScript
  File "_nevs_vpyTemp.vpy", line 9, in <module>
    core.std.LoadPlugin(path=r"LSMASHSource.dll")
  File "src\cython\vapoursynth.pyx", line 1833, in vapoursynth.Function.__call__
vapoursynth.Error: Core only supports API R3.5 but the loaded plugin requires API R3.6; Filename: LSMASHSource.dll; Name: LSMASHSource for VapourSynth

---------------------------------------------------------------------------------------------------------------------------------------
_nevs.mp4
---------------------------------------------------------------------------------------------------------------------------------------
y4m: failed to parse y4m header.
failed to initialize file reader(s).
Failed to open input file.
找不到批处理文件。
```

**Comment by zyzsdy** [comment]
多说两句有关为啥消极压制采用了单一Libs而不是在Libs里面再分类的结构。
其实这就是写程序和人肉管理的区别。我们追求的还是程序分得清就好，你人类能不能分清其实不是很在意。

全部放在一个目录下当然是有意义的，方便各软件使用公共的部分。

比如说`avformat-58.dll`，13.6MB，被nvencc64.exe、qsvencc64.exe、vceencc64.exe、ffmpeg.exe作为共同的依赖，如果上述四个软件分开存放，就会占用54.4MB的空间。
更不要说msvcp140.dll这种是个程序就会依赖的VC运行库了（当然这个不大，只有577KB）

那你可能会问，为啥不用符号链接/软链接？
Windows的软链接很buggy，会出更多的问题。用了就知道。

那你可能又会问，Windows程序自带各种依赖很常见，我电脑里有不下20个mcvcp140.dll，也没见你少带一个啊？
这个问题不仅和Windows二进制程序分发史有关，更和我们程序自身优化有关。我们无从得知您电脑上到底有没有装过这个依赖，而且Windows各程序依赖并没有统一的存放位置，再说我还不一定有权限访问呢，所以稳妥的方式就是自己带上依赖。
但是我自己带上的依赖还是冗余的，就不好了。

因此消极压制短时间内不会将不同程序的安装文件拆分开，在这一时间段内这样做不符合我们的理念。谢谢！

**Comment by BingLingGroup** [comment]
那至少把Vapoursynth和别的分开吧，我没觉着Vapoursynth和别的依赖有什么不可分开的必要，而且我在整理你的依赖的时候发现最难改的也是Vapoursynth，因为自带了一个embeddable python
当然关于VP9的支持这部分我也查了，ffms2最新版也支持了VP9，不过我没看是否修改了API
