### ISSUE TITLE
全局UTF-8编码时 安装程序乱码 / 可能的便携版

### ISSUE THREAD

**Issue by inkydragon** [zyzsdy/NegativeEncoder#39]
效果
![image](https://user-images.githubusercontent.com/5158738/108985952-97602a80-76cc-11eb-8393-3ba797ca5a62.png)

当然安装完成并不影响使用。

如果能打包为便携版的zip，直接解压就无所谓了

**Comment by lonelyion** [comment]
same problem here

**Comment by zyzsdy** [comment]
感谢，问题已确认。安装程序内码是GBK的，在非GBK的环境下确实是会这样的。但是程序本体是用Unicode的，不会产生乱码问题。
除此之外我也考虑一下i18n怎么做吧。

便携版是可以做的，但是要考虑用户配置文件的漫游，目前还不支持自定义用户配置文件保存，这个需要一些工作。如果不介意用户配置，那现在的版本的确可以打个包装走了。

**Comment by zyzsdy** [comment]
现有技术条件下不太好做，等i18n的时候再考虑。安装程序乱码不影响使用。
