### ISSUE TITLE
AVS界面同时压制多个任务

### ISSUE THREAD

**Issue by VegeHime** [zyzsdy/NegativeEncoder#4]
当一个任务正在进行时 再开始另一个任务时两个任务都会很快结束（我试验的几次大概都是压了几百帧）
编码器是QuickSync
（另外，打开文件对话框不选择文件也会弹输入校验错误窗口生成一部分AVS脚本，这个是我强迫症应该 我就顺口一说…）

**Comment by zyzsdy** [comment]
![tim 20180809182328](https://user-images.githubusercontent.com/5925733/43939131-554ea202-9c9a-11e8-81d4-8b0f5601bcad.png)
我自己复现是失败了的。可以看到我这个截图同时有两个avs进程在运行。最好能给出更详细的出错问题时的截图，以及编码框里面的错误提示什么的。

**Comment by VegeHime** [comment]
![image](https://user-images.githubusercontent.com/33897984/43941326-41ffcad0-9ca6-11e8-8ea8-9217ea3dd0ee.png)
我这次复现倒是没两个任务都结束，在第二个任务开始时 第一个就中途结束了
