### ISSUE TITLE
给ffmpeg增加-y参数，以避免ffmpeg碰到已存在的文件时不敢覆盖而产生等待

### ISSUE THREAD

**Issue by zyzsdy** [zyzsdy/NegativeEncoder#43]

**Comment by Last-Order** [comment]
Any updates?

**Comment by A1exMinatoooo** [comment]
![image](https://user-images.githubusercontent.com/21982749/149536063-4b6a510b-c793-4c41-9114-6e13480a5630.png)

Any updates? XD

**Comment by zyzsdy** [comment]
Probably has been fixed in 5.0.4.
