### ISSUE TITLE
新版的5.0.4在64位 windows 7下无法启动

### ISSUE THREAD

**Issue by hongsongshu** [zyzsdy/NegativeEncoder#48]
新版的5.0.4在64位 windows 7下无法启动,卸载了5.0.3后再安装也不行。

**Comment by zyzsdy** [comment]
NegativeEnconder项目从未兼容过Windows 7，所以每一个新版都可能使用了旧版Windows不兼容的组件或代码而导致Windows 7无法启动。

请注意微软官方的Windows 7支持已于2020年1月14日结束。如果是你Windows 7专业版、企业版用户，你可能正在使用Windows 7 SP1 ESU，你可以尝试安装以下三个依赖项：

* [Microsoft Visual C++ 2015-2019 Redistributable](https://aka.ms/vs/16/release/vc_redist.x64.exe)
* [KB3063858](https://www.microsoft.com/download/details.aspx?id=47442)
* [Microsoft 根证书颁发机构2011](https://www.microsoft.com/pkiops/Docs/Repository.htm)

由于开发精力问题，我们不可能有时间兼容每一个停止支持的旧版系统，本项目仅兼容Windows 10 1607以上版本和Windows 11。非常抱歉可能没有解决你的问题，但是我仍然会关闭这个issue并不再开启。
