### ISSUE TITLE
字幕部分建议增加普通VSFilter和VSFilterMod

### ISSUE THREAD

**Issue by qwe7989199** [zyzsdy/NegativeEncoder#6]
VSFilterMod存在一些众所周知的BUG未解决，且效率相比于VSFilter要低不少
建议avs栏，字幕一行加入checkbox，勾选是否使用VSFilterMod
且VSFilterMod版本建议使用https://www.nmm-hd.org/newbbs/viewtopic.php?f=17&t=1989
中的版本，64位未测试

**Comment by zyzsdy** [comment]
added in 7fbe69a
