### ISSUE TITLE
老黄把同时编码的限制开到5个了

### ISSUE THREAD

**Issue by qwe7989199** [zyzsdy/NegativeEncoder#60]
所以默认可以同时开5个任务了，榨干显卡
[消息来源](https://www.tomshardware.com/news/nvidia-increases-concurrent-nvenc-sessions-on-consumer-gpus#:~:text=But%20Nvidia%27s%20stance%20on%20NVENC%20and%20NVDEC%20limitations%20has%20evidently%20changed%20a%20bit.%20Now%2C%20consumer%20GPU%20support%20up%20to%20five%20concurrent%20NVENC%20encode%20sessions.)

**Comment by zyzsdy** [comment]
可以编辑 C:\Users\<Your Username>\AppData\Roaming\NegativeEncoder\Config\Config.json

修改 `MaxEncodingTaskNumber` 的值为 `5`

重启程序后生效。

下个版本将调整此参数的默认值为5。
