### ISSUE TITLE
你好，麻烦帮忙看看这个如何解决？谢谢

### ISSUE THREAD

**Issue by staxrip727** [zyzsdy/NegativeEncoder#71]
https://github.com/rigaya/NVEnc/issues/562

好像发现新大陆，国人沟通就容易多了。
我发现这个编码器有个问题，转码后的文件和源文件帧不同步，我觉得是解码方式的问题。
我用staxrip转码，我有一些下载的录制视频，50FPS，有CFR有VFR，我也不知道这些文件哪里特殊，转完帧不同步。
我帖子贴图那个视频转码后的第一帧比源文件少了近100帧，但是用FFMPEG+NVENC就不会有问题，用shanaencoder handbrake都不会有这个问题，我想是因为他们解码方式不一样？
他这个编码器的优势就是硬解硬压速度快不占用CPU，但是我想转码的大多都是这种录制资源，不同步就难受的很，片头片尾会因此丢失不少帧不能做到和源视频一致。

**Comment by hoshinohikari** [comment]
我看在NVEnc的issue中你已经得到了这个问题的答案，如果这个问题还存在，请携带片源后重新打开issue
